/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cripac_isee_vpe_util_Tracking */

#ifndef _Included_org_cripac_isee_vpe_util_Tracking
#define _Included_org_cripac_isee_vpe_util_Tracking
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cripac_isee_vpe_util_Tracking
 * Method:    readConfFile
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_cripac_isee_vpe_util_Tracking_readConfFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_cripac_isee_vpe_util_Tracking
 * Method:    initialize
 * Signature: (III[BI)J
 */
JNIEXPORT jlong JNICALL Java_org_cripac_isee_vpe_util_Tracking_initialize
  (JNIEnv *, jobject, jint, jint, jint, jbyteArray, jint);

/*
 * Class:     org_cripac_isee_vpe_util_Tracking
 * Method:    dotrack
 * Signature: ([BJ)I
 */
JNIEXPORT jint JNICALL Java_org_cripac_isee_vpe_util_Tracking_dotrack
  (JNIEnv *, jobject, jbyteArray, jlong);

/*
 * Class:     org_cripac_isee_vpe_util_Tracking
 * Method:    getTargets
 * Signature: (J)[Lorg/cripac/isee/vpe/util/Track;
 */
JNIEXPORT jobjectArray JNICALL Java_org_cripac_isee_vpe_util_Tracking_getTargets
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_cripac_isee_vpe_util_Tracking
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_cripac_isee_vpe_util_Tracking_destroy
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
