/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cripac_isee_pedestrian_tracking_ISEEBasicTracker */

#ifndef _Included_org_cripac_isee_pedestrian_tracking_ISEEBasicTracker
#define _Included_org_cripac_isee_pedestrian_tracking_ISEEBasicTracker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cripac_isee_pedestrian_tracking_ISEEBasicTracker
 * Method:    initialize
 * Signature: (III[B)J
 */
JNIEXPORT jlong JNICALL Java_org_cripac_isee_pedestrian_tracking_ISEEBasicTracker_initialize
  (JNIEnv *, jobject, jint, jint, jint, jbyteArray);

/*
 * Class:     org_cripac_isee_pedestrian_tracking_ISEEBasicTracker
 * Method:    feedFrame
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_org_cripac_isee_pedestrian_tracking_ISEEBasicTracker_feedFrame
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     org_cripac_isee_pedestrian_tracking_ISEEBasicTracker
 * Method:    getTargets
 * Signature: (J)[Lorg/cripac/isee/pedestrian/tracking/Tracklet;
 */
JNIEXPORT jobjectArray JNICALL Java_org_cripac_isee_pedestrian_tracking_ISEEBasicTracker_getTargets
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_cripac_isee_pedestrian_tracking_ISEEBasicTracker
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_cripac_isee_pedestrian_tracking_ISEEBasicTracker_free
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
